### ISSUE TITLE
[BUG] exe file not showing anything

### ISSUE THREAD

**Issue by fizzynob** [Official-Husko/Husko-s-SteamWorkshop-Downloader#16] opened 2022-07-10 11:07 UTC
the exe file shows nothing for like 10 seconds and then closes.
![image](https://user-images.githubusercontent.com/104747126/178142353-ea76e8d7-0c9c-40f6-b3c0-59ce4a2e39c5.png)

**Comment by Chechire** [comment] 2022-07-13 12:19
I checked the code
And that's because www.steamworkshopdownloader.io , the website to download items , doesn't work anymore

**Comment by Official-Husko** [comment] 2022-08-26 18:26
> the exe file shows nothing for like 10 seconds and then closes. ![image](https://user-images.githubusercontent.com/104747126/178142353-ea76e8d7-0c9c-40f6-b3c0-59ce4a2e39c5.png)

I am aware of that and i made the changes to the readme to reflect this issue as of now. If you want to read more into the project status you can do that on the readme [here](https://github.com/Official-Husko/Husko-s-SteamWorkshop-Downloader#important)



> I checked the code And that's because [www.steamworkshopdownloader.io](http://www.steamworkshopdownloader.io) , the website to download items , doesn't work anymore

that is correct yes, this check was implemented a day before they took down their services and since i did not except such a thing while coding it crashes.

**Comment by Official-Husko** [comment] 2022-11-23 15:12
Duplicate of #10

**Closed as completed by Official-Husko** 2022-11-23 15:12 UTC
Labels: bug
