### ISSUE TITLE
[BUG] Crashing on start

### ISSUE THREAD

**Issue by AnCarsenat** [Official-Husko/Husko-s-SteamWorkshop-Downloader#17] opened 2022-11-20 14:11 UTC
**Describe the bug**
When i run the Exe it stops and closes

**To Reproduce**
RUN the Exe file

**Expected behavior**
Run the Exe file and allow me to downoald

**Screenshots**
![BUG](https://user-images.githubusercontent.com/87574028/202906845-0a684487-2ec2-4778-998d-03a5a86c6fd1.png)

**Desktop (please complete the following information):**
 Windwows 10

**Additional context**

**Comment by Official-Husko** [comment] 2022-11-23 15:13
Duplicate of #10

**Closed as completed by Official-Husko** 2022-11-23 15:13 UTC
Labels: bug
