### ISSUE TITLE
[BUG] Windows 11 64 bit

### ISSUE THREAD

**Issue by adiestadih** [Official-Husko/Husko-s-SteamWorkshop-Downloader#15] opened 2022-06-30 12:07 UTC
On windows 11 not working

**Comment by RoonMoonlight** [comment] 2022-06-30 12:09
Where is a log? Where is details

**Comment by adiestadih** [comment] 2022-06-30 14:47
i downloaded the exe file when i run it open cmd for a while then cmd closed by itself. no message appears. I tried to right click run as administrator, the result is still the same, no message appears. Thank you

**Comment by RoonMoonlight** [comment] 2022-06-30 14:55
It does not work because this project is on hold

It might have been broken as the time has passed

All you can do is to wait until the project is being resumed

**Comment by adiestadih** [comment] 2022-06-30 14:57
Okay, okay hope it will be released soon because so many are waiting. Thank you for your time

**Comment by Official-Husko** [comment] 2022-07-05 11:57
> Okay, okay hope it will be released soon because so many are waiting. Thank you for your time

The issue you are reporting is due to a backend check for the servers from steamworkshopdownloader.io. When i added that i didn't expect for them to shut it down immeadiatly therefor i didn't have a safetynet in place to catch the exception. 

Or in simple words. it crashes for everyone currently due to the steamworkshopdownloader.io
Im working on the steamcmd method for now which should hopefully be done soon

**Comment by Yoon0117** [comment] 2022-07-08 11:21
> i downloaded the exe file when i run it open cmd for a while then cmd closed by itself. no message appears. I tried to right click run as administrator, the result is still the same, no message appears. Thank you

Same Happens For me

**Comment by Yoon0117** [comment] 2022-07-08 11:22
> > Okay, okay hope it will be released soon because so many are waiting. Thank you for your time
> 
> The issue you are reporting is due to a backend check for the servers from steamworkshopdownloader.io. When i added that i didn't expect for them to shut it down immeadiatly therefor i didn't have a safetynet in place to catch the exception.
> 
> Or in simple words. it crashes for everyone currently due to the steamworkshopdownloader.io Im working on the steamcmd method for now which should hopefully be done soon

oh ok

**Comment by Official-Husko** [comment] 2022-11-23 15:12
Duplicate of #10

**Closed as completed by Official-Husko** 2022-11-23 15:12 UTC
Labels: bug
